apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-logs-role
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-logs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy-logs-role
subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.relabel "pod_logs" {
      targets = discovery.kubernetes.pods.targets

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        regex         = "moneysaver-api"
        action        = "keep"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_node_name"]
        target_label  = "node"
      }
      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label  = "container"
      }

      rule {
        action      = "labelmap"
        regex       = "__meta_kubernetes_pod_label_(app_kubernetes_io_name|app_kubernetes_io_component|app|name|component)"
        replacement = "$1"
      }

      rule {
        source_labels = [
          "__meta_kubernetes_namespace",
          "__meta_kubernetes_pod_name",
          "__meta_kubernetes_pod_uid",
          "__meta_kubernetes_pod_container_name",
        ]
        separator     = "/"
        regex         = "(.*)/(.*)/(.*)/(.*)"
        replacement   = "/var/log/pods/${1}_${2}_${3}/${4}/*.log"
        target_label  = "__path__"
      }
    }

    local.file_match "pod_logs" {
      path_targets = discovery.relabel.pod_logs.output
    }

    loki.source.file "pod_logs" {
      targets    = local.file_match.pod_logs.targets
      forward_to = [loki.process.cluster_logs.receiver]
    }
    loki.process "cluster_logs" {
      forward_to = [loki.write.loki_endpoint.receiver]
      stage.cri {}
    }

    loki.write "loki_endpoint" {
      external_labels = {
        cluster = "my-kubernetes-cluster",
      }
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        batch_size = "1MB"
        batch_wait = "1s"
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      containers:
        - name: alloy
          image: grafana/alloy:latest
          securityContext:
            runAsUser: 0                     # Запускаем от root для доступа к /var/log
            allowPrivilegeEscalation: false  # Запрещаем дочерним процессам получать больше прав
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/var/lib/alloy/data
            - --server.http.listen-addr=0.0.0.0:12345
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 12345
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: alloy-data
              mountPath: /var/lib/alloy/data
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: alloy-data
          hostPath:
            path: /var/lib/alloy/data
            type: DirectoryOrCreate