services:
  backend:
    container_name: MoneySaver
    build:
      context: ./
      dockerfile: Dockerfile
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
  reverse-proxy:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    restart: "unless-stopped"
    networks:
      - default
    depends_on:
      backend:
          condition: service_healthy
    volumes:
      - "./nginx:/etc/nginx"