services:
  backend:
    container_name: MoneySaver
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: "always"
    healthcheck:
      test: "curl http://localhost:8000/healthcheck/readiness"
      interval: 10s
      timeout: 5s
      retries: 5
  reverse-proxy:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    restart: "always"
    networks:
      - default
    depends_on:
      - backend
    volumes:
      - "./nginx:/etc/nginx"