services:
  database:
    container_name: MoneySaverDatabase
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - default
    ports:
      - "5429:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
  migration:
    container_name: MoneySaverMigrator
    build:
      context: ./
      dockerfile: Dockerfile
    command: uv run alembic upgrade head
    depends_on:
      database:
        condition: service_healthy
    environment:
      LOG_LEVEL: INFO
      DB_HOST: database
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
  backend:
    container_name: MoneySaverBackend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: "unless-stopped"
    depends_on:
      database:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
    environment:
      LOG_LEVEL: INFO
      DB_HOST: database
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
  reverse-proxy:
    container_name: MoneySaverNginx
    image: nginx:latest
    ports:
      - "80:80"
    restart: "unless-stopped"
    networks:
      - default
    depends_on:
      backend:
          condition: service_healthy
    volumes:
      - "./nginx:/etc/nginx"
  loki:
    image: grafana/loki:3.0.0
    container_name: MoneySaverLoki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - monitoring
  alloy:
    image: grafana/alloy:latest
    container_name: MoneySaverAlloy
    privileged: true
    volumes:
      - ./monitoring/config/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "run", "--server.http.listen-addr=0.0.0.0:12345", "/etc/alloy/config.alloy" ]
    networks:
      - monitoring
    depends_on:
      - loki
  grafana:
    image: grafana/grafana:latest
    container_name: MoneySaverGrafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana.ini:/etc/grafana/grafana.ini
      - ./monitoring/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - monitoring
      - default
    depends_on:
      - loki

volumes:
  db:
  loki_data:
  grafana_data:
  postgres_data:

networks:
  monitoring: