"""empty message

Revision ID: 543db013ba2b
Revises: ec0ec4998fc1
Create Date: 2026-05-14 00:48:20.858640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543db013ba2b'
down_revision: Union[str, Sequence[str], None] = 'ec0ec4998fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ix_limit_user_name', 'limits', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_limit_user_name', 'limits', type_='unique')
    # ### end Alembic commands ###
